### ISSUE TITLE
Calling local server travel files on startup

### ISSUE THREAD

**Issue by TheRoam** [wwwouaiebe/leaflet.TravelNotes#177]
Is there a way I could load a travel file that is hosted in the same server as the map, rather than a local file? Doing it at startup would be great.

Im still making my way through the code, understanding how things work and how to customise it a little. This is a fine job, congrats!

**Comment by wwwouaiebe** [comment]
It's possible to open a travel file that is located on the server, but the file is opened in read only mode. The user interface and all the context menus are disabled (see the user guides).
I have just released the v3.0.0 version. Now the code is completely based on objects and don't use anymore closures and 'constructor' functions as in the v2.3.0 version.
The entry point is the method addReadOnlyMap ( ) of the TravelNotes class ( in the main/TravelNotes.js file)  when a file is loaded from the server and the addControl ( ) method of the same class when no file is loaded. I think it's not to mutch difficult to create another method that open a distant file for read and write, but saving the file to the server will be difficult (development on the server file is needed and I see a lot of security problems).
It's possible that opening a distant travel don't works in the v2.3.0 version, due to a missing 'await' keyword in a function.

**Comment by TheRoam** [comment]
hi, I managed to tweak the code and it now automatically loads a specific server file and also saves any changes when pressed saved. I did it creating two separate functions that use the File API to update the content of the "input" file element (im not very experienced in programming, but it works)

I might fork when I have all tweaks finished (most of them are css for mobile integration), but this issue can be closed for my case.

Thanks for your reply and the great job, it is really impressive when you dive into the code.
